---
- name: Install common packages
  hosts: swarm
  roles:
    - common
    - docker

- name: Configure Manager
  hosts: swarm-managers
  roles:
  - dockermanager

- name: Configure Workers
  hosts: swarm-workers
  roles:
    - dockerworker

- name: Create GlusterFS on hosts
  hosts: swarm
  roles:
    - glusterfs

- name: Create swarm services
  hosts: swarm-managers
  roles:
    - swarm_services
